version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8-openjdk-11

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Build and Run Tests
          command: mvn test

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - codecov/upload:
          requires:
            - build
